sudo: false
language: python
python:
    - "2.7"
addons:
    apt:
        packages:
            - libboost-serialization-dev
            - libboost-regex-dev
            - libboost-thread-dev
            - libboost-python-dev
            - libboost-system-dev
            - libboost-filesystem-dev
            - libboost-test-dev
            - cmake
script:
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release ..
   - make
   - ctest .
